// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export interface AllPathDto {
    "SliceMp4Path": string;
    "M3u8Dir": string;
    "UniqueName": string;
    "M3u8VideoBasePath": string;
    "MergeEndPath": string;
    "MergeDecPath": string;
    "M3u8VideoPathTpl": string;
    "CoverImagePathTpl": string;
}

export interface ExtListItem {
    "Path": string;
    "StartSec": number;
    "StartTimeStr": string;
    "ExtDuration": number;
    "ExtKeyUri": string;
    "ExtKeyTrue": string;
    "ExtKeyIvTrue": string;
    "ExtDiscontinuity": boolean;
}

/**
 * #EXT-X-VERSION:3：HLS 协议版本号（常见为 3 或以上）。
 * #EXT-X-TARGETDURATION:10：所有媒体分片的最大持续时间（秒）。
 * #EXT-X-MEDIA-SEQUENCE:0：第一个分片的序列号（用于直播流）。
 * #EXT-X-PLAYLIST-TYPE:VOD：播放列表类型（VOD 点播或 EVENT 直播事件）。
 * #EXT-X-ENDLIST：表示播放列表结束（仅限点播，直播中无此标签）。
 * #EXTINF: 10.000，：媒体分片的持续时间（秒）。
 * #EXT-X-DISCONTINUITY：表示分片 discontinuity（分片 discontinuity）。
 * #EXT-X-KEY:METHOD=AES-128,URI="pathxxx",IV=xxx ：定义解密密钥（若流被加密）。
 */
export interface M3u8Info {
    "ExtVersion": number;
    "ExtTargetduration": number;
    "ExtMediaSequence": number;
    "ExtPlaylistType": string;
    "ExtList": { [_ in string]?: ExtListItem[] };
    "ExtListLen": number;
}
