// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as common$0 from "./common/models.js";

/**
 * 检查ffmpeg是否安装
 */
export function CheckFfmpeg(): $CancellablePromise<void> {
    return $Call.ByID(4155590157);
}

/**
 * 检测m3u8文件
 */
export function CheckM3u8File(path: string): $CancellablePromise<string> {
    return $Call.ByID(2127423907, path);
}

/**
 * 清空m3u8文件作业
 */
export function ClearM3u8FileJob(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(4275194281, path);
}

/**
 * 删除当前作业数据源
 */
export function DeleteM3u8Source(path: string): $CancellablePromise<any> {
    return $Call.ByID(1870563535, path);
}

/**
 * 			playPathList = append(playPathList, playPathListItem)
 * 			// fmt.Println("m3u8VideoPath=", m3u8VideoPath)
 * 			// fmt.Println("m3u8Dir=", m3u8Dir)
 * 		}
 * 		return playPathList, nil
 * 	}
 */
export function DoGetM3u8SliceVideoV2(path: string, pathDto: common$0.AllPathDto | null, listSlice: common$0.ExtListItem[], optType: string): $CancellablePromise<{ [_ in string]?: any }[]> {
    return $Call.ByID(310088911, path, pathDto, listSlice, optType).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetGetAllPathDto(path: string, ...listMapKey: string[]): $CancellablePromise<common$0.AllPathDto | null> {
    return $Call.ByID(226839173, path, listMapKey);
}

/**
 * 合并每个已经生成m3u8任务文件
 */
export function MergeM3u8File(path: string, finalMergeFileList: string[]): $CancellablePromise<any> {
    return $Call.ByID(2199319543, path, finalMergeFileList);
}

/**
 * 打开m3u8文件
 */
export function OpenM3u8File(path: string): $CancellablePromise<any> {
    return $Call.ByID(3019273563, path);
}

/**
 * 解析m3u8文件
 */
export function ParseM3u8File(path: string, content: string | null): $CancellablePromise<[common$0.M3u8Info | null, string[]]> {
    return $Call.ByID(1951774624, path, content).then(($result: any) => {
        $result[0] = $$createType5($result[0]);
        $result[1] = $$createType6($result[1]);
        return $result;
    });
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Map($Create.Any, $$createType2);
const $$createType4 = $Create.Struct({
    "ExtList": $$createType3,
});
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($Create.Any);
