// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function MessageDialog(msg: string, title: string): $CancellablePromise<void> {
    return $Call.ByID(2069387988, msg, title);
}

/**
 * OpenFileDialog
 */
export function OpenFileDialog(optionJson: { [_ in string]?: any }): $CancellablePromise<string> {
    return $Call.ByID(1019573019, optionJson);
}
