// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function MessageDialog(arg1, arg2) {
  return window['go']['goApi']['Runtime']['MessageDialog'](arg1, arg2);
}

export function OpenFileDialog(arg1) {
  return window['go']['goApi']['Runtime']['OpenFileDialog'](arg1);
}
